import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Q1: 觀察測試(test)資料集和訓練(Train)資料集的變數的差異性?
df_train = pd.read_csv("Titanic_train.csv")
df_test = pd.read_csv("Titanic_test.csv")
print(df_train.info())
print(df_test.info())
print("由上可知df_test差一欄column=Survived")
df1 = df_train.drop_duplicates(subset = None, keep = "first", inplace = False  )
df2 = df_test.drop_duplicates(subset = None, keep = "first", inplace = False  )
if df1.shape[1] == df_train.shape[1] :
    print("沒有重覆")
if df2.shape[1] == df_test.shape[1] :
    print("沒有重覆")
print(df_train.duplicated())
print(df_test.duplicated())
# Q2: 測試資料集是否有遺失值?
print(df_train.isnull().head(5))
print(df_test.isnull().head(5))
print(df_train.isnull().any())
print(df_train.isnull().any().sum())
print(df_test.isnull().any())
print(df_test.isnull().any().sum())
df_train = df_train.replace('null',np.NaN)
df_test = df_test.replace('null',np.NaN)
print(df_train[df_train.isnull().values == True])
print(df_test[df_test.isnull().values == True])
# Q3: 從合併資料選取一個變數，嘗試去做各種不同遺失值的處理，
# 並透過圖形或數值來做輔助判斷，補值前與後的差異，你覺得以這個變數而言，試著說明每一個方法的差異。
data = pd.concat([df_train,df_test],ignore_index=True)
print(data)
print(data['Age'].mean())
print(data['Age'].std())
g = sns.FacetGrid(data, col = 'Sex')
g.map(sns.distplot,'Age',kde = False)
plt.show()
#Age缺失值補0,因為補0平均值變低,0低於平均數太多變異數隨之變大
data['Age'] = data['Age'].fillna(0)
print(data['Age'].mean())
print(data['Age'].std())
g = sns.FacetGrid(data, col = 'Sex')
g.map(sns.distplot,'Age',kde = False)
plt.show()
#Age缺失值補平均數,平均值等於原本的平均值,因補平均值所以變異數變小
df_train = pd.read_csv("Titanic_train.csv")
df_test = pd.read_csv("Titanic_test.csv")
data = pd.concat([df_train,df_test],ignore_index=True)
data['Age'] = data['Age'].fillna(data['Age'].mean())
print(data['Age'].mean())
print(data['Age'].std())
g = sns.FacetGrid(data,col='Sex')
g.map(sns.distplot,'Age', kde = False)
plt.show()
#Age缺失值由前往後補,平均值與變異數,不太有變化,代表補值都在平均值附近
df_train = pd.read_csv("Titanic_train.csv")
df_test = pd.read_csv("Titanic_test.csv")
data = pd.concat([df_train,df_test],ignore_index=True)
data['Age'] = data['Age'].fillna(method ='bfill')
print(data['Age'].mean())
print(data['Age'].std())
g = sns.FacetGrid(data,col='Sex')
g.map(sns.distplot,'Age', kde = False)
plt.show()
#Age缺失值由後往前補,平均值與變異數,不太有變化,代表補值都在平均值附近
df_train = pd.read_csv("Titanic_train.csv")
df_test = pd.read_csv("Titanic_test.csv")
data = pd.concat([df_train,df_test],ignore_index=True)
data['Age'] = data['Age'].fillna(method ='pad')
print(data['Age'].mean())
print(data['Age'].std())
g = sns.FacetGrid(data,col='Sex')
g.map(sns.distplot,'Age', kde = False)
plt.show()

print(data['Cabin'].isnull())
print(data['Cabin'].isnull().sum())
print(data['Cabin'].value_counts())
print(np.sum(data.isnull()))
data['Cabin'] = data['Cabin'].apply(lambda x : str(x) if not pd.isnull(x) else '沒有船艙' )
print(data['Cabin'].isnull())
print(data['Cabin'].isnull().sum())
print(data['Cabin'].value_counts())
print(np.sum(data.isnull()))